mysql_backup: Remove old *.gz backups

diff --git a/bin/mysql_backup b/bin/mysql_backup
--- a/bin/mysql_backup
+++ b/bin/mysql_backup
@@ -80,7 +80,7 @@ done
 
 if [[ $fail -eq 0 ]]; then
 	_ssh "$remote" "$(printf 'touch %q' "${dir}mysql.ok")" || fail=1
-	_ssh "$remote" "$(printf 'find %q -maxdepth 1 -type f -name "*.tmp" -mmin +1440 -delete' "${dir}mysql")" || fail=1
+	_ssh "$remote" "$(printf 'find %q -maxdepth 1 -type f \( -name "*.tmp" -or -name "*.gz" \) -mmin +1440 -delete' "${dir}mysql")" || fail=1
 fi
 
 if [[ $fail -eq 1 ]]; then
